#!/usr/bin/env bash
#
# configure-openclaw.sh — 一键把 OpenClaw 接到 LiveToken (macOS / Linux / WSL)
#
# 做的事：
#   1. 检查 OpenClaw 是否安装；缺则用 npm 装一份
#   2. 让你贴一个 LiveToken API Key（或读已有的 LIVETOKEN_API_KEY）
#   3. 备份现有 ~/.openclaw/openclaw.json
#   4. 写入新的 openclaw.json，把 LiveToken 注册为默认 provider
#      默认模型：claude-sonnet-4-5
#      端点：https://livetoken.top（Anthropic Messages 兼容）
#   5. 把 LIVETOKEN_API_KEY append 进 ~/.zshrc 或 ~/.bashrc
#
# 用法：
#   ./configure-openclaw.sh                                    # 交互式
#   ./configure-openclaw.sh --api-key sk-... --model claude-sonnet-4-5
#   API_KEY=sk-... ./configure-openclaw.sh                     # 也支持环境变量

set -euo pipefail

# ---------- args ----------
API_KEY="${API_KEY:-}"
BASE_URL="https://livetoken.top"
DEFAULT_MODEL="claude-sonnet-4-5"
SKIP_INSTALL=0
NO_RC=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-key)        API_KEY="$2"; shift 2 ;;
    --base-url)       BASE_URL="$2"; shift 2 ;;
    --model)          DEFAULT_MODEL="$2"; shift 2 ;;
    --skip-install)   SKIP_INSTALL=1; shift ;;
    --no-rc)          NO_RC=1; shift ;;
    -h|--help)
      head -n 16 "$0" | sed 's/^#//;s/^!.*//'
      exit 0 ;;
    *) echo "未知参数: $1" >&2; exit 2 ;;
  esac
done

# ---------- pretty ----------
c_cyan="\033[1;36m"; c_green="\033[1;32m"; c_yellow="\033[1;33m"; c_red="\033[1;31m"; c_reset="\033[0m"
step()  { printf "\n${c_cyan}==> %s${c_reset}\n" "$1"; }
ok()    { printf "    ${c_green}[ok]${c_reset} %s\n" "$1"; }
warn()  { printf "    ${c_yellow}[warn]${c_reset} %s\n" "$1"; }
fail()  { printf "    ${c_red}[fail]${c_reset} %s\n" "$1" >&2; }

# ---------- 1. ensure openclaw ----------
step "检查 OpenClaw"
if command -v openclaw >/dev/null 2>&1; then
  ver="$(openclaw --version 2>/dev/null || true)"
  ok "已检测到 OpenClaw${ver:+: $ver}"
elif [[ $SKIP_INSTALL -eq 1 ]]; then
  warn "未检测到 openclaw 命令（跳过安装由 --skip-install 指定）"
else
  if ! command -v npm >/dev/null 2>&1; then
    fail "系统里没有 npm。先装 Node.js (建议 brew install node / apt install nodejs npm) 再回头跑本脚本。"
    exit 1
  fi
  warn "未检测到 openclaw 命令，尝试 npm i -g openclaw …"
  if ! npm install -g openclaw; then
    fail "npm 装 openclaw 失败。也可以试官方一键: curl -fsSL https://openclaw.ai/install.sh | bash"
    exit 1
  fi
  ok "已经把 openclaw 装到 npm 全局目录"
fi

# ---------- 2. resolve key ----------
step "取 LiveToken API Key"
if [[ -z "$API_KEY" ]]; then
  API_KEY="${LIVETOKEN_API_KEY:-${ANTHROPIC_API_KEY:-}}"
  if [[ -n "$API_KEY" ]]; then
    warn "未传 --api-key，复用环境变量里已有的 LIVETOKEN_API_KEY/ANTHROPIC_API_KEY"
  fi
fi
if [[ -z "$API_KEY" ]]; then
  printf "请粘贴 LiveToken API Key (注册: https://livetoken.top): "
  stty -echo
  read -r API_KEY
  stty echo
  printf "\n"
fi
API_KEY="${API_KEY// /}"
[[ -z "$API_KEY" ]] && { fail "API Key 为空，退出。"; exit 1; }

if [[ ! "$API_KEY" =~ ^sk- ]] && [[ ${#API_KEY} -lt 32 ]]; then
  warn "Key 看起来不像 LiveToken (一般以 sk- 开头)。仍然继续，但调用可能 401。"
fi

mask="***"
if [[ ${#API_KEY} -ge 8 ]]; then
  mask="${API_KEY:0:2}***${API_KEY: -4}"
fi
ok "Key 已读取: $mask"

# ---------- 3. write config ----------
step "写入 OpenClaw 配置"
home_dir="${HOME:-/}"
config_dir="$home_dir/.openclaw"
config_path="$config_dir/openclaw.json"
mkdir -p "$config_dir"

if [[ -f "$config_path" ]]; then
  stamp="$(date +%Y%m%d-%H%M%S)"
  cp "$config_path" "$config_path.bak.$stamp"
  ok "已备份旧配置 → $config_path.bak.$stamp"
fi

cat > "$config_path" <<JSON
{
  "\$schema": "https://docs.openclaw.ai/schema/openclaw.json",
  "\$comment": "Generated by ai-installer / configure-openclaw.sh — 默认用 LiveToken 提供的模型。",
  "models": {
    "providers": {
      "livetoken": {
        "name": "LiveToken",
        "baseUrl": "$BASE_URL",
        "compatibility": "anthropic",
        "models": [
          { "id": "claude-sonnet-4-5", "name": "Claude Sonnet 4.5 (via LiveToken)" },
          { "id": "claude-opus-4-5",   "name": "Claude Opus 4.5 (via LiveToken)" },
          { "id": "claude-haiku-4-5",  "name": "Claude Haiku 4.5 (via LiveToken)" }
        ]
      }
    }
  },
  "auth": {
    "profiles": {
      "livetoken:default": {
        "provider": "livetoken",
        "mode": "api_key",
        "keyRef": { "source": "env", "provider": "default", "id": "LIVETOKEN_API_KEY" }
      }
    }
  },
  "agents": {
    "defaults": {
      "model": { "provider": "livetoken", "id": "$DEFAULT_MODEL" }
    }
  }
}
JSON
ok "已写入 $config_path"

# ---------- 4. persist key in shell rc ----------
if [[ $NO_RC -eq 0 ]]; then
  step "写入 LIVETOKEN_API_KEY 到 shell rc"

  # Pick rc file: prefer zshrc on macOS / when SHELL is zsh, else bashrc
  rc_file=""
  case "${SHELL:-}" in
    */zsh)  rc_file="$home_dir/.zshrc" ;;
    */bash) rc_file="$home_dir/.bashrc" ;;
    *)
      if [[ -f "$home_dir/.zshrc" ]]; then rc_file="$home_dir/.zshrc"
      elif [[ -f "$home_dir/.bashrc" ]]; then rc_file="$home_dir/.bashrc"
      elif [[ "$(uname)" == "Darwin" ]]; then rc_file="$home_dir/.zshrc"
      else rc_file="$home_dir/.bashrc"
      fi
      ;;
  esac

  touch "$rc_file"
  marker="# >>> ai-installer / livetoken >>>"
  end_marker="# <<< ai-installer / livetoken <<<"

  # Strip any previous block (idempotent)
  if grep -qF "$marker" "$rc_file"; then
    awk -v m="$marker" -v e="$end_marker" '
      $0 == m {skip=1; next}
      skip && $0 == e {skip=0; next}
      !skip {print}
    ' "$rc_file" > "$rc_file.tmp" && mv "$rc_file.tmp" "$rc_file"
  fi

  {
    printf "\n%s\n" "$marker"
    printf "export LIVETOKEN_API_KEY=%q\n" "$API_KEY"
    printf "%s\n" "$end_marker"
  } >> "$rc_file"

  ok "已在 $rc_file 写入 LIVETOKEN_API_KEY=$mask"
  warn "注意：只对新打开的终端生效，或者跑 \`source $rc_file\`。"
else
  warn "已跳过 shell rc 写入 (--no-rc)。OpenClaw 启动前请手动 export LIVETOKEN_API_KEY=…"
fi

# ---------- 5. summary ----------
step "完成"
printf "
  Provider     : livetoken (anthropic-compatible)
  Base URL     : %s
  Default model: %s
  Config       : %s
  Key (env)    : LIVETOKEN_API_KEY = %s

下一步：
  1. 关掉当前终端，新开一个 (或 source 一下 rc)
  2. 跑：openclaw onboard --skip-provider
     或： openclaw agent run \"hello\"
  3. 余额/用量看 https://livetoken.top 控制台
" "$BASE_URL" "$DEFAULT_MODEL" "$config_path" "$mask"
