<#
  configure-openclaw.ps1 — 一键把 OpenClaw 接到 LiveToken

  做的事：
    1. 检查 OpenClaw 是否安装；缺则用 npm 装一份
    2. 让你贴一个 LiveToken API Key（或读已有的 LIVETOKEN_API_KEY）
    3. 备份现有 ~/.openclaw/openclaw.json
    4. 写入新的 openclaw.json，把 LiveToken 注册为默认 provider
       默认模型：claude-sonnet-4-5
       端点：https://livetoken.top（Anthropic Messages 兼容）
    5. 把 LIVETOKEN_API_KEY 写进 Windows 用户环境变量

  用法：
    .\configure-openclaw.ps1                                    # 交互式
    .\configure-openclaw.ps1 -ApiKey 'sk-...' -DefaultModel 'claude-sonnet-4-5'
    .\configure-openclaw.ps1 -BaseUrl 'https://livetoken.top'   # 改端点

  执行策略提示：
    如果脚本被阻止运行，先在 PowerShell 跑一次：
        Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned
    或者一次性绕过：
        powershell -ExecutionPolicy Bypass -File .\configure-openclaw.ps1
#>

[CmdletBinding()]
param(
  [string]$ApiKey,
  [string]$BaseUrl = 'https://livetoken.top',
  [string]$DefaultModel = 'claude-sonnet-4-5',
  [switch]$SkipInstall,
  [switch]$NoEnvVar
)

$ErrorActionPreference = 'Stop'

function Write-Step {
  param([string]$Msg)
  Write-Host ''
  Write-Host "==> $Msg" -ForegroundColor Cyan
}

function Write-Ok {
  param([string]$Msg)
  Write-Host "    [ok] $Msg" -ForegroundColor Green
}

function Write-Warn2 {
  param([string]$Msg)
  Write-Host "    [warn] $Msg" -ForegroundColor Yellow
}

function Write-Fail {
  param([string]$Msg)
  Write-Host "    [fail] $Msg" -ForegroundColor Red
}

# ---------------------------------------------------------------------------
# 1. Ensure OpenClaw is installed
# ---------------------------------------------------------------------------
Write-Step '检查 OpenClaw'

function Test-Command {
  param([string]$Name)
  $cmd = Get-Command $Name -ErrorAction SilentlyContinue
  return [bool]$cmd
}

$hasOpenclaw = Test-Command 'openclaw'

if (-not $hasOpenclaw -and -not $SkipInstall) {
  if (-not (Test-Command 'npm')) {
    Write-Fail '系统里没有 npm。请先装 Node.js（或直接跑 ai-installer 的 Claude 安装器），再回头跑本脚本。'
    Write-Host '    https://github.com/OnelongX/ai-installer/releases/latest'
    exit 1
  }

  Write-Warn2 '未检测到 openclaw 命令，尝试 npm i -g openclaw …'
  & npm install -g openclaw
  if ($LASTEXITCODE -ne 0) {
    Write-Fail 'npm 安装 openclaw 失败，看上面的日志。也可以用官方一键脚本：'
    Write-Host '    iwr -useb https://openclaw.ai/install.ps1 | iex'
    exit 1
  }
  Write-Ok '已经把 openclaw 装到 npm 全局目录'
} elseif ($hasOpenclaw) {
  $ver = & openclaw --version 2>$null
  if ($LASTEXITCODE -eq 0 -and $ver) {
    Write-Ok "已检测到 OpenClaw: $($ver.Trim())"
  } else {
    Write-Ok '已检测到 openclaw 命令'
  }
}

# ---------------------------------------------------------------------------
# 2. Resolve API key
# ---------------------------------------------------------------------------
Write-Step '取 LiveToken API Key'

if (-not $ApiKey) {
  $ApiKey = [Environment]::GetEnvironmentVariable('LIVETOKEN_API_KEY', 'User')
}

if (-not $ApiKey) {
  $ApiKey = [Environment]::GetEnvironmentVariable('ANTHROPIC_API_KEY', 'User')
  if ($ApiKey) {
    Write-Warn2 "未传 -ApiKey，但发现已有 ANTHROPIC_API_KEY，复用它。"
  }
}

if (-not $ApiKey) {
  $secure = Read-Host '请粘贴 LiveToken API Key（注册：https://livetoken.top）' -AsSecureString
  $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try {
    $ApiKey = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
  } finally {
    [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }
}

$ApiKey = $ApiKey.Trim()

if (-not $ApiKey) {
  Write-Fail 'API Key 为空，退出。'
  exit 1
}

if (-not ($ApiKey.StartsWith('sk-') -or $ApiKey.Length -ge 32)) {
  Write-Warn2 'Key 格式看起来不像 LiveToken 的（一般以 sk- 开头）。仍然继续，但 LiveToken 调用可能会 401。'
}

$mask = if ($ApiKey.Length -ge 8) {
  "$($ApiKey.Substring(0, 2))***$($ApiKey.Substring($ApiKey.Length - 4))"
} else {
  '***'
}
Write-Ok "Key 已读取: $mask"

# ---------------------------------------------------------------------------
# 3. Write ~/.openclaw/openclaw.json
# ---------------------------------------------------------------------------
Write-Step '写入 OpenClaw 配置'

$home_dir = $env:USERPROFILE
if (-not $home_dir) { $home_dir = [Environment]::GetFolderPath('UserProfile') }
$openclawDir = Join-Path $home_dir '.openclaw'
$configPath = Join-Path $openclawDir 'openclaw.json'

if (-not (Test-Path $openclawDir)) {
  New-Item -Path $openclawDir -ItemType Directory -Force | Out-Null
}

if (Test-Path $configPath) {
  $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
  $backupPath = "$configPath.bak.$stamp"
  Copy-Item $configPath $backupPath
  Write-Ok "已备份旧配置 → $backupPath"
}

$config = [ordered]@{
  '$schema' = 'https://docs.openclaw.ai/schema/openclaw.json'
  '$comment' = 'Generated by ai-installer / configure-openclaw.ps1 — 默认用 LiveToken 提供的模型。'
  models = [ordered]@{
    providers = [ordered]@{
      livetoken = [ordered]@{
        name = 'LiveToken'
        baseUrl = $BaseUrl
        compatibility = 'anthropic'
        models = @(
          [ordered]@{ id = 'claude-sonnet-4-5'; name = 'Claude Sonnet 4.5 (via LiveToken)' }
          [ordered]@{ id = 'claude-opus-4-5';   name = 'Claude Opus 4.5 (via LiveToken)' }
          [ordered]@{ id = 'claude-haiku-4-5';  name = 'Claude Haiku 4.5 (via LiveToken)' }
        )
      }
    }
  }
  auth = [ordered]@{
    profiles = [ordered]@{
      'livetoken:default' = [ordered]@{
        provider = 'livetoken'
        mode = 'api_key'
        keyRef = [ordered]@{
          source = 'env'
          provider = 'default'
          id = 'LIVETOKEN_API_KEY'
        }
      }
    }
  }
  agents = [ordered]@{
    defaults = [ordered]@{
      model = [ordered]@{
        provider = 'livetoken'
        id = $DefaultModel
      }
    }
  }
}

$json = $config | ConvertTo-Json -Depth 10
# Force UTF-8 (no BOM) so JSON5 parsers don't choke
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($configPath, $json, $utf8NoBom)
Write-Ok "已写入 $configPath"

# ---------------------------------------------------------------------------
# 4. Persist LIVETOKEN_API_KEY in user env
# ---------------------------------------------------------------------------
if (-not $NoEnvVar) {
  Write-Step '写入 LIVETOKEN_API_KEY 用户环境变量'
  [Environment]::SetEnvironmentVariable('LIVETOKEN_API_KEY', $ApiKey, 'User')
  Write-Ok "已写入用户环境变量 LIVETOKEN_API_KEY = $mask"
  Write-Warn2 '注意：环境变量只对新打开的终端窗口生效。'
} else {
  Write-Warn2 '已跳过环境变量写入（-NoEnvVar）。OpenClaw 启动前请手动 export LIVETOKEN_API_KEY=…'
}

# ---------------------------------------------------------------------------
# 5. Summary
# ---------------------------------------------------------------------------
Write-Step '完成'

Write-Host ''
Write-Host '  Provider     : livetoken (anthropic-compatible)' -ForegroundColor White
Write-Host "  Base URL     : $BaseUrl" -ForegroundColor White
Write-Host "  Default model: $DefaultModel" -ForegroundColor White
Write-Host "  Config       : $configPath" -ForegroundColor White
Write-Host "  Key (env)    : LIVETOKEN_API_KEY = $mask" -ForegroundColor White
Write-Host ''
Write-Host '下一步：' -ForegroundColor Cyan
Write-Host '  1. 关掉当前这个 PowerShell 窗口，重新开一个（让环境变量生效）'
Write-Host '  2. 跑：openclaw onboard --skip-provider     # 跳过自带 provider 引导'
Write-Host '     或： openclaw agent run "hello"          # 直接试一句'
Write-Host '  3. 余额/用量看 https://livetoken.top 控制台'
Write-Host ''
Write-Host '想换默认模型？再跑一次本脚本加 -DefaultModel claude-opus-4-5。'
