#!/usr/bin/env bash
# configure-aider.sh — 一键把 Aider 接到 LiveToken (macOS / Linux / WSL)
#
# 做的事：
#   1. 检测 Aider；缺则 pip install -U aider-chat
#   2. 取 LiveToken API Key
#   3. 写 ~/.aider.conf.yml
#   4. 把 ANTHROPIC_API_KEY + ANTHROPIC_API_BASE append 进 ~/.zshrc / ~/.bashrc

set -euo pipefail

API_KEY="${API_KEY:-}"
BASE_URL="https://livetoken.top"
DEFAULT_MODEL="anthropic/claude-sonnet-4-5"
WEAK_MODEL="anthropic/claude-haiku-4-5"
SKIP_INSTALL=0
NO_RC=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-key)      API_KEY="$2"; shift 2 ;;
    --base-url)     BASE_URL="$2"; shift 2 ;;
    --model)        DEFAULT_MODEL="$2"; shift 2 ;;
    --weak-model)   WEAK_MODEL="$2"; shift 2 ;;
    --skip-install) SKIP_INSTALL=1; shift ;;
    --no-rc)        NO_RC=1; shift ;;
    -h|--help) head -n 10 "$0" | sed 's/^#//;s/^!.*//'; exit 0 ;;
    *) echo "未知参数: $1" >&2; exit 2 ;;
  esac
done

c=$'\033'; cyan="${c}[1;36m"; green="${c}[1;32m"; yellow="${c}[1;33m"; red="${c}[1;31m"; reset="${c}[0m"
step()  { printf "\n${cyan}==> %s${reset}\n" "$1"; }
ok()    { printf "    ${green}[ok]${reset} %s\n" "$1"; }
warn()  { printf "    ${yellow}[warn]${reset} %s\n" "$1"; }
fail()  { printf "    ${red}[fail]${reset} %s\n" "$1" >&2; }

# 1. ensure aider
step "检查 Aider"
if command -v aider >/dev/null 2>&1; then
  ver="$(aider --version 2>/dev/null | head -1 || true)"
  ok "已检测到 Aider${ver:+: $ver}"
elif [[ $SKIP_INSTALL -eq 1 ]]; then
  warn "未检测到 aider 命令（跳过安装由 --skip-install 指定）"
else
  pip_cmd=""
  for c in pip3 pip; do
    if command -v "$c" >/dev/null 2>&1; then pip_cmd="$c"; break; fi
  done
  if [[ -z "$pip_cmd" ]] && command -v python3 >/dev/null 2>&1; then
    pip_cmd="python3 -m pip"
  fi
  if [[ -z "$pip_cmd" ]]; then
    fail "没有 pip。先装 Python 3：macOS 用 brew install python；Linux 用 apt install python3-pip / dnf install python3-pip。"
    exit 1
  fi
  warn "未检测到 aider 命令，尝试 $pip_cmd install -U aider-chat …"
  $pip_cmd install -U aider-chat
  ok "已 pip install -U aider-chat"
fi

# 2. resolve key
step "取 LiveToken API Key"
if [[ -z "$API_KEY" ]]; then
  API_KEY="${LIVETOKEN_API_KEY:-${ANTHROPIC_API_KEY:-}}"
  [[ -n "$API_KEY" ]] && warn "复用已有的环境变量里的 Key"
fi
if [[ -z "$API_KEY" ]]; then
  printf "请粘贴 LiveToken API Key (注册: https://livetoken.top): "
  stty -echo; read -r API_KEY; stty echo; printf "\n"
fi
API_KEY="${API_KEY// /}"
[[ -z "$API_KEY" ]] && { fail "API Key 为空"; exit 1; }

mask="***"
[[ ${#API_KEY} -ge 8 ]] && mask="${API_KEY:0:2}***${API_KEY: -4}"
ok "Key 已读取: $mask"

# 3. write ~/.aider.conf.yml
step "写入 ~/.aider.conf.yml"
home_dir="${HOME:-/}"
conf="$home_dir/.aider.conf.yml"
if [[ -f "$conf" ]]; then
  stamp="$(date +%Y%m%d-%H%M%S)"
  cp "$conf" "$conf.bak.$stamp"
  ok "已备份旧配置 → $conf.bak.$stamp"
fi

cat > "$conf" <<YAML
# Generated by ai-installer / configure-aider.sh — LiveToken defaults
model: $DEFAULT_MODEL
weak-model: $WEAK_MODEL
edit-format: diff
auto-commits: true
dirty-commits: true
gitignore: true
analytics: false
YAML
ok "已写入 $conf"

# 4. env vars
if [[ $NO_RC -eq 0 ]]; then
  step "写入 ANTHROPIC_API_KEY + ANTHROPIC_API_BASE 到 shell rc"
  rc=""
  case "${SHELL:-}" in
    */zsh)  rc="$home_dir/.zshrc" ;;
    */bash) rc="$home_dir/.bashrc" ;;
    *)
      if [[ -f "$home_dir/.zshrc" ]]; then rc="$home_dir/.zshrc"
      elif [[ -f "$home_dir/.bashrc" ]]; then rc="$home_dir/.bashrc"
      elif [[ "$(uname)" == "Darwin" ]]; then rc="$home_dir/.zshrc"
      else rc="$home_dir/.bashrc"
      fi
      ;;
  esac
  touch "$rc"
  marker="# >>> ai-installer / aider / livetoken >>>"
  end="# <<< ai-installer / aider / livetoken <<<"
  if grep -qF "$marker" "$rc"; then
    awk -v m="$marker" -v e="$end" '$0==m{skip=1;next} skip && $0==e{skip=0;next} !skip{print}' "$rc" > "$rc.tmp" && mv "$rc.tmp" "$rc"
  fi
  {
    printf "\n%s\n" "$marker"
    printf "export ANTHROPIC_API_KEY=%q\n" "$API_KEY"
    printf "export ANTHROPIC_API_BASE=%q\n" "$BASE_URL"
    printf "export LIVETOKEN_API_KEY=%q\n" "$API_KEY"
    printf "%s\n" "$end"
  } >> "$rc"
  ok "已在 $rc 写入 ANTHROPIC_API_KEY=$mask + ANTHROPIC_API_BASE=$BASE_URL"
  warn "只对新打开的终端生效，或 source $rc"
fi

step "完成"
printf "
  Default model: %s
  Weak model   : %s
  Base URL     : %s
  Config       : %s
  Key (env)    : ANTHROPIC_API_KEY = %s

下一步：
  1. 新开终端 (或 source rc)
  2. cd 到 git 仓库
  3. 跑：aider
" "$DEFAULT_MODEL" "$WEAK_MODEL" "$BASE_URL" "$conf" "$mask"
