<#
  configure-aider.ps1 — 一键把 Aider 接到 LiveToken (Windows)

  做的事：
    1. 检测 Aider 是否安装；缺则 pip install -U aider-chat
    2. 取 LiveToken API Key
    3. 写 ~/.aider.conf.yml （默认 model = anthropic/claude-sonnet-4-5）
    4. 把 ANTHROPIC_API_KEY + ANTHROPIC_API_BASE 写到 Windows 用户环境变量
       （Aider 底层用 litellm，走 Anthropic 兼容路径）

  用法：
    .\configure-aider.ps1
    .\configure-aider.ps1 -ApiKey 'sk-...' -DefaultModel 'anthropic/claude-sonnet-4-5'
#>

[CmdletBinding()]
param(
  [string]$ApiKey,
  [string]$BaseUrl = 'https://livetoken.top',
  [string]$DefaultModel = 'anthropic/claude-sonnet-4-5',
  [string]$WeakModel = 'anthropic/claude-haiku-4-5',
  [switch]$SkipInstall,
  [switch]$NoEnvVar
)

$ErrorActionPreference = 'Stop'

function Write-Step { param($m) Write-Host ''; Write-Host "==> $m" -ForegroundColor Cyan }
function Write-Ok   { param($m) Write-Host "    [ok] $m"   -ForegroundColor Green }
function Write-Warn2{ param($m) Write-Host "    [warn] $m" -ForegroundColor Yellow }
function Write-Fail { param($m) Write-Host "    [fail] $m" -ForegroundColor Red }
function Has-Cmd    { param($n) [bool](Get-Command $n -ErrorAction SilentlyContinue) }

# 1. ensure aider
Write-Step '检查 Aider'
if (Has-Cmd 'aider' -and -not $SkipInstall) {
  $ver = & aider --version 2>$null
  Write-Ok "已检测到 Aider${(if($ver){`": ${($ver -join ' ').Trim()}`"}else{''})}"
} elseif (-not $SkipInstall) {
  $pipCmd = $null
  foreach ($c in 'pip','pip3','py') {
    if (Has-Cmd $c) { $pipCmd = $c; break }
  }
  if (-not $pipCmd) {
    Write-Fail 'Python / pip 没装。先装 Python (https://www.python.org/downloads/ 或 winget install Python.Python.3.12) 再回头。'
    exit 1
  }
  Write-Warn2 "未检测到 aider 命令，尝试 $pipCmd install -U aider-chat …"
  if ($pipCmd -eq 'py') { & py -m pip install -U aider-chat } else { & $pipCmd install -U aider-chat }
  if ($LASTEXITCODE -ne 0) {
    Write-Fail "$pipCmd 装 aider-chat 失败，看上面的日志"
    exit 1
  }
  Write-Ok '已经 pip install -U aider-chat'
}

# 2. resolve key
Write-Step '取 LiveToken API Key'
if (-not $ApiKey) {
  $ApiKey = [Environment]::GetEnvironmentVariable('LIVETOKEN_API_KEY', 'User')
  if (-not $ApiKey) { $ApiKey = [Environment]::GetEnvironmentVariable('ANTHROPIC_API_KEY', 'User') }
  if ($ApiKey) { Write-Warn2 '复用已有的环境变量里的 Key' }
}
if (-not $ApiKey) {
  $secure = Read-Host '请粘贴 LiveToken API Key (注册: https://livetoken.top)' -AsSecureString
  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try { $ApiKey = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr) }
  finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
}
$ApiKey = $ApiKey.Trim()
if (-not $ApiKey) { Write-Fail 'API Key 为空'; exit 1 }

$mask = if ($ApiKey.Length -ge 8) { "$($ApiKey.Substring(0,2))***$($ApiKey.Substring($ApiKey.Length-4))" } else { '***' }
Write-Ok "Key 已读取: $mask"

# 3. write ~/.aider.conf.yml
Write-Step '写入 ~/.aider.conf.yml'
$home_dir = $env:USERPROFILE
$confPath = Join-Path $home_dir '.aider.conf.yml'
if (Test-Path $confPath) {
  $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
  Copy-Item $confPath "$confPath.bak.$stamp"
  Write-Ok "已备份旧配置 → $confPath.bak.$stamp"
}

@"
# Generated by ai-installer / configure-aider.ps1 — LiveToken defaults
model: $DefaultModel
weak-model: $WeakModel
edit-format: diff
auto-commits: true
dirty-commits: true
gitignore: true
# 不发遥测，避免 prefix cache 干扰
analytics: false
"@ | Set-Content -Path $confPath -Encoding utf8
Write-Ok "已写入 $confPath"

# 4. env vars
if (-not $NoEnvVar) {
  Write-Step '写入 ANTHROPIC_API_KEY + ANTHROPIC_API_BASE'
  [Environment]::SetEnvironmentVariable('ANTHROPIC_API_KEY',  $ApiKey,  'User')
  [Environment]::SetEnvironmentVariable('ANTHROPIC_API_BASE', $BaseUrl, 'User')
  [Environment]::SetEnvironmentVariable('LIVETOKEN_API_KEY',  $ApiKey,  'User')
  Write-Ok "ANTHROPIC_API_KEY = $mask"
  Write-Ok "ANTHROPIC_API_BASE = $BaseUrl"
  Write-Warn2 '注意：环境变量只对新打开的终端生效。'
}

Write-Step '完成'
Write-Host ''
Write-Host "  Default model: $DefaultModel" -ForegroundColor White
Write-Host "  Weak model   : $WeakModel"    -ForegroundColor White
Write-Host "  Base URL     : $BaseUrl"      -ForegroundColor White
Write-Host "  Config       : $confPath"     -ForegroundColor White
Write-Host ''
Write-Host '下一步：' -ForegroundColor Cyan
Write-Host '  1. 新开 PowerShell 让环境变量生效'
Write-Host '  2. cd 到任何 git 仓库，跑：aider'
Write-Host '  3. 检查：aider --models / aider --help'
