#!/usr/bin/env bash
#
# install_codex.sh — 一行命令在 macOS / Linux / WSL 上把 Codex CLI 装到位
#
# 做的事和 Windows 上的 Codex 安装器一一对位：
#   1. 检测 / 安装 Node.js (brew / apt / dnf / pacman / zypper / fnm 兜底)
#   2. npm i -g @openai/codex
#   3. 写 ~/.codex/config.toml (LiveToken provider + gpt-5.5 high)
#   4. 把 OPENAI_API_KEY 写进 ~/.zshrc / ~/.bashrc
#   5. 跑 codex --version 验证
#
# 也存在一个老 Python 脚本 install_codex_macos.py，那个只装 CLI 不配 LiveToken。
# 推荐用本脚本（bash，macOS + Linux 通用，配置完整）。
#
# 用法：
#   ./install_codex.sh                                          # 交互式
#   ./install_codex.sh --api-key sk-xxx
#   curl -fsSL https://raw.githubusercontent.com/OnelongX/ai-installer/main/codex/install_codex.sh | bash -s -- --api-key sk-xxx

set -euo pipefail

API_KEY="${API_KEY:-}"
BASE_URL="https://livetoken.top/v1"
DEFAULT_MODEL="gpt-5.5"
NPM_PACKAGE="@openai/codex"
SKIP_NODE=0
SKIP_RC=0
NON_INTERACTIVE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-key)         API_KEY="$2"; shift 2 ;;
    --base-url)        BASE_URL="$2"; shift 2 ;;
    --model)           DEFAULT_MODEL="$2"; shift 2 ;;
    --skip-node)       SKIP_NODE=1; shift ;;
    --skip-rc)         SKIP_RC=1; shift ;;
    --non-interactive) NON_INTERACTIVE=1; shift ;;
    -h|--help) sed -n '2,20p' "$0" | sed 's/^#\s\?//'; exit 0 ;;
    *) echo "未知参数: $1" >&2; exit 2 ;;
  esac
done

c=$'\033'; cyan="${c}[1;36m"; green="${c}[1;32m"; yellow="${c}[1;33m"; red="${c}[1;31m"; reset="${c}[0m"
step()  { printf "\n${cyan}==> %s${reset}\n" "$1"; }
ok()    { printf "    ${green}[ok]${reset} %s\n" "$1"; }
warn()  { printf "    ${yellow}[warn]${reset} %s\n" "$1"; }
fail()  { printf "    ${red}[fail]${reset} %s\n" "$1" >&2; }
has()   { command -v "$1" >/dev/null 2>&1; }

# 0. platform check
OS="$(uname -s)"
case "$OS" in
  Darwin|Linux) ;;
  *) fail "不支持的系统：$OS。本脚本面向 macOS / Linux / WSL；Windows 请用 Codex 安装器。"; exit 1 ;;
esac

# 1. ensure node
step "检测 Node.js / npm"
if has node && has npm; then
  ok "Node.js $(node -v) / npm $(npm -v) 已就位"
elif [[ $SKIP_NODE -eq 1 ]]; then
  fail "未检测到 node / npm，且 --skip-node 指定。先手动装好 Node 20+ 再回头。"
  exit 1
else
  warn "未检测到 Node.js，自动安装…"
  installed=0
  if [[ "$OS" == "Darwin" ]]; then
    if has brew; then
      step "brew install node"
      brew install node && installed=1
    fi
  else
    if has apt-get; then
      step "apt-get install nodejs"
      if has curl; then
        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - && sudo apt-get install -y nodejs && installed=1
      else
        sudo apt-get update && sudo apt-get install -y nodejs npm && installed=1
      fi
    elif has dnf; then
      sudo dnf install -y nodejs npm && installed=1
    elif has pacman; then
      sudo pacman -S --noconfirm nodejs npm && installed=1
    elif has zypper; then
      sudo zypper install -y nodejs npm && installed=1
    fi
  fi
  if [[ $installed -ne 1 ]]; then
    warn "包管理器装 Node 没成。回落到 fnm。"
    if ! has fnm; then
      curl -fsSL https://fnm.vercel.app/install | bash
      export PATH="$HOME/.local/share/fnm:$PATH"
      eval "$(fnm env --use-on-cd 2>/dev/null || true)"
    fi
    if has fnm; then
      fnm install --lts
      fnm use lts-latest
      eval "$(fnm env)"
    fi
  fi
  if ! has node || ! has npm; then
    fail "Node 装完了还是找不到。重新打开终端再试。"
    exit 1
  fi
  ok "Node.js $(node -v) / npm $(npm -v)"
fi

# 2. resolve key
step "取 LiveToken API Key"
if [[ -z "$API_KEY" ]]; then
  API_KEY="${LIVETOKEN_API_KEY:-${OPENAI_API_KEY:-${ANTHROPIC_API_KEY:-}}}"
  [[ -n "$API_KEY" ]] && warn "复用环境变量里已有的 Key"
fi
if [[ -z "$API_KEY" ]]; then
  if [[ $NON_INTERACTIVE -eq 1 ]]; then
    fail "非交互模式下必须传 --api-key。"
    exit 1
  fi
  printf "请粘贴 LiveToken API Key (注册: https://livetoken.top): "
  stty -echo; read -r API_KEY; stty echo; printf "\n"
fi
API_KEY="${API_KEY// /}"
[[ -z "$API_KEY" ]] && { fail "API Key 为空"; exit 1; }
mask="***"
[[ ${#API_KEY} -ge 8 ]] && mask="${API_KEY:0:2}***${API_KEY: -4}"
ok "Key 已读取: $mask"

# 3. install codex CLI
step "安装 $NPM_PACKAGE"
npm install -g "$NPM_PACKAGE"
ok "npm i -g $NPM_PACKAGE 完成"

# 4. write ~/.codex/config.toml
step "写入 ~/.codex/config.toml"
home_dir="${HOME:-/}"
conf_dir="$home_dir/.codex"
conf="$conf_dir/config.toml"
mkdir -p "$conf_dir"
if [[ -f "$conf" ]]; then
  stamp="$(date +%Y%m%d-%H%M%S)"
  cp "$conf" "$conf.bak.$stamp"
  ok "已备份 → $conf.bak.$stamp"
fi

cat > "$conf" <<TOML
# Generated by ai-installer / install_codex.sh — LiveToken provider defaults
personality = "pragmatic"
model = "$DEFAULT_MODEL"
model_provider = "cm"
review_model = "$DEFAULT_MODEL"
model_reasoning_effort = "high"
plan_mode_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"
model_verbosity = "medium"
model_supports_reasoning_summaries = true
approval_policy = "on-request"
allow_login_shell = true
sandbox_mode = "workspace-write"
cli_auth_credentials_store = "file"
chatgpt_base_url = "https://chatgpt.com/backend-api/"
mcp_oauth_credentials_store = "auto"
check_for_update_on_startup = true
web_search = "live"
approvals_reviewer = "user"
service_tier = "fast"

[model_providers.cm]
approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "live"
name = "LiveToken"
base_url = "$BASE_URL"
wire_api = "responses"
env_key = "OPENAI_API_KEY"
TOML
ok "已写入 $conf"

# 5. shell rc
if [[ $SKIP_RC -eq 0 ]]; then
  step "写入 OPENAI_API_KEY 到 shell rc"
  rc=""
  case "${SHELL:-}" in
    */zsh)  rc="$home_dir/.zshrc" ;;
    */bash) rc="$home_dir/.bashrc" ;;
    *)
      if [[ -f "$home_dir/.zshrc" ]]; then rc="$home_dir/.zshrc"
      elif [[ -f "$home_dir/.bashrc" ]]; then rc="$home_dir/.bashrc"
      elif [[ "$OS" == "Darwin" ]]; then rc="$home_dir/.zshrc"
      else rc="$home_dir/.bashrc"
      fi
      ;;
  esac
  touch "$rc"
  marker="# >>> ai-installer / codex / livetoken >>>"
  end="# <<< ai-installer / codex / livetoken <<<"
  if grep -qF "$marker" "$rc"; then
    awk -v m="$marker" -v e="$end" '$0==m{skip=1;next} skip && $0==e{skip=0;next} !skip{print}' "$rc" > "$rc.tmp" && mv "$rc.tmp" "$rc"
  fi
  {
    printf "\n%s\n" "$marker"
    printf "export OPENAI_API_KEY=%q\n" "$API_KEY"
    printf "export LIVETOKEN_API_KEY=%q\n" "$API_KEY"
    printf "%s\n" "$end"
  } >> "$rc"
  ok "已在 $rc 写入 OPENAI_API_KEY=$mask"
  warn "只对新打开的终端生效，或 source $rc"
else
  warn "已跳过 shell rc 写入 (--skip-rc)"
fi

# 6. verify
step "验证"
if codex_ver="$(codex --version 2>&1)"; then
  ok "codex --version → $codex_ver"
else
  warn "codex --version 没跑通。可能 PATH 还没刷新——重新打开终端再试。"
fi

step "完成"
printf "
  CLI version  : %s
  Default model: %s
  Base URL     : %s
  Config       : %s
  Key (env)    : OPENAI_API_KEY = %s

下一步：
  1. 关掉这个终端，新开一个 (或 source rc)
  2. cd 到任何项目目录跑：codex
" "${codex_ver:-unknown}" "$DEFAULT_MODEL" "$BASE_URL" "$conf" "$mask"
